name: Ken Planter
favicon: null
layout_spectrum: 0.49489
typography_spectrum: 0.23555
title: Video thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03080b'
    - '#33524c'
    - '#52c09b'
    - '#f0e2b5'
    - '#b24572'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
