name: Ken Planter
favicon: null
layout_spectrum: 0.49489
typography_spectrum: 0.23555
title: Video thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6c49f'
    - '#97847d'
    - '#78584b'
    - '#3f270f'
    - '#abb700'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
