name: Ken Planter
favicon: null
layout_spectrum: 0.25639
typography_spectrum: 0.23555
title: Video thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060d0d'
    - '#8e9fbb'
    - '#4b514d'
    - '#28805c'
    - '#fffefc'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
