name: Ken Planter
favicon: null
layout_spectrum: 0.2482
typography_spectrum: 0.91596
title: Video thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#393939'
    - '#666666'
    - '#767676'
    - '#8a8a8a'
  brandStrength: 0
  lightness: 0.1555523402057588
  saturation: 0.6803714486304671
  rhythmicContrast: 0.5
purpose: []
