name: Ken Planter
favicon: null
layout_spectrum: 0.49489
typography_spectrum: 0.23555
title: Video thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fde794'
    - '#101010'
    - '#a49d8d'
    - '#365166'
    - '#637f8a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
